name 'Analytical Labs-postgresql'
version '1.0'

author 'Tom Barber'
license ''
project_page ''
source ''
summary ''
description ''
dependency 'Analytical Labs/sudo', '==1.0'
dependency 'Analytical Labs/apt', '==1.0'
